/**
 * Offline service worker.
 *
 * The whole app — shell, all chapter content, all figures, all icons — is
 * precached on install. It is small enough to fit comfortably, and caching it
 * whole means there is no half-offline state to explain to someone standing in
 * a field with no signal: either the app installed or it did not.
 *
 * ASSETS and CACHE are regenerated by tools/build-sw.mjs. Do not edit the
 * marked block by hand; run `node tools/build-sw.mjs` after adding content.
 */

/* --- generated:begin --- */
const CACHE = 'opwiki-936c9276a0';
const ASSETS = [
  './',
  'css/app.css',
  'data/ch01.json',
  'data/ch02.json',
  'data/ch03.json',
  'data/ch04.json',
  'data/ch05.json',
  'data/ch06.json',
  'data/ch07.json',
  'data/ch08.json',
  'data/ch09.json',
  'data/ch10.json',
  'data/ch11.json',
  'data/ch12.json',
  'data/ch13.json',
  'data/ch14.json',
  'data/ch15.json',
  'data/ch16.json',
  'data/ch17.json',
  'data/ch18.json',
  'data/ch19.json',
  'data/ch20.json',
  'data/index.json',
  'favicon.ico',
  'icons/apple-touch-icon-180.png',
  'icons/favicon-32.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-192.png',
  'icons/icon-maskable-512.png',
  'icons/splash/1125x2436-dark.png',
  'icons/splash/1125x2436-light.png',
  'icons/splash/1170x2532-dark.png',
  'icons/splash/1170x2532-light.png',
  'icons/splash/1179x2556-dark.png',
  'icons/splash/1179x2556-light.png',
  'icons/splash/1242x2688-dark.png',
  'icons/splash/1242x2688-light.png',
  'icons/splash/1284x2778-dark.png',
  'icons/splash/1284x2778-light.png',
  'icons/splash/1290x2796-dark.png',
  'icons/splash/1290x2796-light.png',
  'icons/splash/1536x2048-dark.png',
  'icons/splash/1536x2048-light.png',
  'icons/splash/1668x2388-dark.png',
  'icons/splash/1668x2388-light.png',
  'icons/splash/2048x2732-dark.png',
  'icons/splash/2048x2732-light.png',
  'icons/splash/750x1334-dark.png',
  'icons/splash/750x1334-light.png',
  'icons/splash/828x1792-dark.png',
  'icons/splash/828x1792-light.png',
  'index.html',
  'js/app.js',
  'js/charts.js',
  'js/config.js',
  'js/content.js',
  'js/i18n.js',
  'js/prefs.js',
  'js/qrcode.js',
  'js/search.js',
  'manifest.webmanifest',
];
/* --- generated:end --- */

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: one 404 would leave the app half-installed, so assets
    // are added individually and failures are reported rather than fatal.
    const results = await Promise.allSettled(
      ASSETS.map(url => cache.add(new Request(url, { cache: 'reload' })))
    );
    const failed = results
      .map((r, i) => (r.status === 'rejected' ? ASSETS[i] : null))
      .filter(Boolean);
    if (failed.length) console.warn('[sw] could not precache:', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    // Every app on bryanwoo988.github.io shares this origin's Cache Storage:
    // delete only this app's own old versions, never another app's offline copy.
    await Promise.all(names.filter(n => n.startsWith('opwiki-') && n !== CACHE).map(n => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;   // the Info screen's link

  // A deep link opened offline must still resolve to the shell, which then
  // routes on the hash.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const root = new URL('./', self.location);
      const isRoot = url.pathname === root.pathname ||
                     url.pathname === `${root.pathname}index.html`;

      // The app's own URL is served from the cache, so it opens instantly and
      // works with no network. Every route in this app lives in the fragment,
      // so this is the only path the app itself ever navigates to.
      if (isRoot) {
        const cached = await caches.match('index.html');
        if (cached) return cached;
      }

      try {
        // Any other path goes to the network: there are real pages here that
        // are deliberately not precached, such as tests/.
        return await fetch(request);
      } catch {
        // Offline. Handing the shell back at a nested path would leave its
        // relative css/ and js/ resolving against that depth, where nothing
        // exists — an unstyled, empty page. Redirecting to the scope root fixes
        // them, and the browser carries the fragment across the redirect.
        if (!isRoot) return Response.redirect(root.pathname + url.search, 302);
        const cached = await caches.match('index.html');
        return cached ?? new Response('Offline', { status: 503, statusText: 'Offline' });
      }
    })());
    return;
  }

  event.respondWith((async () => {
    // Only what install put in the cache is served from it. There is
    // deliberately no opportunistic caching of other responses: the app is
    // precached in full, so it would add nothing, and it would quietly pin a
    // stale copy of anything else fetched once — including this worker's own
    // script and the pages under tests/.
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(request);
    } catch {
      return new Response('', { status: 504, statusText: 'Offline' });
    }
  })());
});
